### ISSUE TITLE
MRO::Magic fails on Perl blead due to use of smartmatch operator

### ISSUE THREAD

**Issue by jkeenan** [rjbs/MRO-Magic#1]
Sample report:
http://www.cpantesters.org/cpan/report/5f1f1624-5ce5-11ef-9907-ff996c135b50

Smartmatch operator being removed from Perl effective immediately.  It's used at line 159 lib/MRO/Magic.pm, perhaps elsewhere.

**Comment by rjbs** [comment]
I've fixed this in git, but this library is wildly experimental and spews warnings like a stuck pig.  Anybody who was using this up until the ~~ thing… was already having a bad day. 😉
